name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  riverpod: ^2.5.1
  shared_preferences: ^2.0.6
  flutter_map: ^4.0.0
  latlong2: ^0.8.0
  http: ^0.13.4
  permission_handler: ^10.2.0
  local_auth: ^2.1.6
  table_calendar: ^3.0.0
  google_nav_bar: ^5.0.6
  mercadopago_sdk: ^1.0.2
  url_launcher: ^6.0.17
  intl: ^0.17.0
  geolocator: ^8.2.0
  flutter_custom_tabs: ^2.1.0

  

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/car_logo.png
    - assets/images/bot.png
    - assets/images/frenteOdeon.png
    - assets/images/garage2.png
    - assets/images/garage3.png